### PR TITLE
Implement default map with exits

### LINKED ISSUE #1: Mapper module
Fill out `Mapper.ts`
The Mapper is responsible for creating the layout of the structure. It should be able to make us some walls and exits.

Currently, there are four walls that form a barrier around the whole screen.
We need to change this to have openings (how large?) and call them `exits`. Then export the array of `exits` so that our `Persons` can find them:
```js
export const exits = []
// push the exits to the array
```
We also need to answer the question of scale. What are the dimensions? How large should the `Person` object be? This should be communicated to the whomever is implementing the `Person` class.

### PR DESCRIPTION
**Pull request by adurso3**
Closes #1.

I've made a default map that essentially divides the space in half, with a way to reach each half. A simple barrier to impede traffic flow exists, and two exits in the top right and left corner exist.

I imagine what we'll end up doing is having a default map (or two), then have an option to import a map into the system. As such, I've gone ahead and renamed some things in the initial code shells. We can worry about customability at a later date.

### CODE REVIEW

**Comment by Bkucera** [comment]
Can you run 
```
npm build
```
Then copy the `dist` folder into the docs folder and rename the folder `5`
So we have docs->5->index.html
Then you can do `git add docs` and commit with message "Deploy #5"
So we can see this deployed by going to kuc.io/CX4230-evac-sim/5/index.html 
?

**Comment by Bkucera** [comment]
I will have this automated with circle CI soon :)

**Comment by Bkucera** [comment]
So this is mostly my bad, but we should make the Sim a fixed size so that the size of the browser window doesn't affect the running of the test. also the `exits` should be much smaller because the Person size is so much smaller right now

**Comment by Bkucera** [comment]
Live at https://kuc.io/CX4230-evac-sim/5/

**Comment by adurso3** [comment]
This has been merged with #7.

**Pull request closed without merging**
